### ISSUE TITLE
UAS

### ISSUE THREAD

**Issue by hasanalrasyid** [istibsyaro/Istibsyaro-jaringanEnterpriseK02#17]
1. Identifikasi Risiko Keamanan dalam jaringan ini. Anda bisa ambil asumsi Zero Trust, yang berarti tidak ada mesin yang dapat dipercaya dalam jaringan, terutama mesin yang dikendalikan oleh manusia. Anda bisa memulai dari identifikasi peran, mis. Admin Nilai, Server Utama, Admin Prodi, Client Pegawai Biasa, mesin Absensi, mesin perekam video, dsb. Risiko yang paling nyata adalah adanya peluang orang yang tak bertanggung-jawab masuk ke dalam jaringan sebagai pegawai biasa atau mahasiswa dan dapat mengakses server penyimpan data utama atau berbagai mesin yang terhubung jaringan yang sama. Berikan pemaparan risiko yang lebih terperinci.
2. Tanpa mengubah infrastruktur fisik, anda dapat melakukan segmentasi jaringan untuk meningkatkan keamanan. Bagaimana arsitektur yang anda tawarkan? Buat tabel yang menunjukkan zonasi, segmen IP dan pembatasan akses yang diberlakukan.

Contoh:
| Zone   | Server Utama | Server Nilai ...dst |
|-----|-----|----|
|Kaprodi  |  Read/Write  | Read/Write |
| Admin Nilai | Read/Write  |     |
| Admin Laboratorium | Read/Write? | |
| Dosen | RW terbatas |   |
| dst...|     |   |

3. Solusi apa yang bisa anda tawarkan jika ada dosen yang menghadiri seminar di luar kampus, dan memerlukan akses data realtime dan terhubung ke jaringan internal/server di gedung yang terkait? Bagaimana arsitektur implementasi yang anda tawarkan? Apa saja risiko yang perlu dipertimbangkan?
4. Tanpa mengubah infrastruktur fisik yang ada, perusahaan ini menyediakan akses internet kepada tamu istimewa prodi dan kepada mahasiswa prodi. Dengan tetap mempertimbangkan faktor keamanan, solusi apa yang bisa anda tawarkan? Bagaimana arsitektur topologinya? Bagaimana segmentasi jaringannya? Apa saja batasan yang perlu diberikan kepada segmen "TAMU" ini?
5. Kampus ingin menerapkan penggunaan mesin absensi realtime terpusat dari server utama di gedung ketiga (di luar gedung yang ada), namun masih ada dalam jaringan kampus, untuk memperoleh data realtime dari setiap mesin absensi dari semua gedung. Untuk sementara 3 mesin telah siap, dan akan dikembangkan ke mesin lain. Untuk ini diperlukan Server Utama yang mengolah dan mengumpulkan data. Bagaimana arsitektur solusi yang anda tawarkan? Identifikasi risiko keamanan yang muncul, dalam asumsi bahwa semua zona punya potensi menjadi titik pintu masuk ancaman.

Selamat berkarya,

HAR

**Comment by hayyunshofi** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/hayyun/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/hayyun/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/hayyun/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-ID style='tab-interval:36.0pt;word-wrap:break-word'>


<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal align=center style='text-align:center'><b><span
style='font-size:16.0pt;line-height:107%;font-family:"Times New Roman",serif'>Jawaban<o:p></o:p></span></b></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>(1).</span></b><span
style='font-family:"Times New Roman",serif'><span style='mso-spacerun:yes'> 
</span>setiap jaringan yang ada di fakultas tehnik itu menggunakan mikrotik
yang mana di dalam settingannya menggunakan 2 metode, yang pertama metode user
dan kedua admin. Dengan adanya 2 metode ini maka secarah teknis sulit untuk
bisa mengakses ke server karna bagian server hanya bisa di lihat oleh admin
sedangkan di topologi fakultas itu menggunakan metode user. di dalam jaringan
fakultas tehnik juga menggunakan remot control untuk ip addres,kecepatan
jaringan dll dengan adanya remot itu bisa mengetahui ip mana yang melakukan
pengambilan data dll,<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>(2). <o:p></o:p></span></b></p>



Zone | Server   Utama | Server   Nilai ...dst
-- | -- | --
Kaprodi | 192.168.1.0/24 | -   Akses   bebas antar perangkat dalam zona Internal
Admin   Nilai | 192.168.2.0/24 | -   Akses terbatas dari Admin Nilai ke Internal
Admin   Laboratorium | 192.168.3.0/24 | - Akses terbatas   dari External ke server publik di Admin Laboratorium
Dosen |   | -   Hanya diizinkan mengirim data absensi ke Server Utama di Gedung Ketiga



<p class=MsoNormal style='text-align:justify'><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>Catatan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>A. Segmen IP dapat
disesuaikan sesuai dengan kebutuhan jaringan dan jumlah perangkat di setiap
zona.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>B. Firewall harus
dikonfigurasi dengan bijak untuk menerapkan pembatasan akses sesuai dengan
tabel di atas. Firewall di antara zona-zona ini akan bertindak sebagai pengawal
yang memastikan lalu lintas hanya diperbolehkan sesuai dengan kebijakan
keamanan yang telah ditetapkan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>(3).</span></b><span
style='font-family:"Times New Roman",serif'><span style='mso-spacerun:yes'> 
</span>Untuk solusi akses data real-time dan terhubung ke jaringan
internal/server di gedung terkait bagi seorang dosen yang menghadiri seminar di
luar kampus, ada beberapa opsi arsitektur implementasi yang dapat diusulkan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>A.
VPN (Virtual Private Network):<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Solusi
ini memungkinkan dosen untuk terhubung ke jaringan internal kampus melalui
internet secara aman. Dosen dapat menggunakan perangkat seperti laptop atau
smartphone untuk mengakses server dan data internal kampus dengan aman melalui
koneksi VPN.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Arsitektur
implementasi melibatkan konfigurasi VPN server di gedung kampus dan klien VPN
pada perangkat dosen.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>B.
Remote Desktop Services (RDS):<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Dosen
dapat menggunakan Remote Desktop Services untuk mengakses komputer yang berada
di dalam gedung kampus. Dosen akan dapat mengontrol komputer dari jarak jauh menggunakan
perangkat yang dibawanya (laptop atau tablet).<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Arsitektur
implementasi memerlukan konfigurasi server RDS di dalam gedung kampus yang
dapat diakses dari luar kampus melalui koneksi internet yang aman.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Risiko
yang perlu dipertimbangkan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>C.
Cloud-Based Solutions:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Data
dan aplikasi kampus dapat dipindahkan ke lingkungan cloud yang aman dan dapat
diakses dari mana saja dengan koneksi internet. Beberapa penyedia layanan cloud
menawarkan solusi jaringan khusus untuk menghubungkan cloud dengan jaringan
internal kampus.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Dosen
dapat mengakses data real-time dan aplikasi yang terhosting di cloud dengan
mudah dari lokasi seminar.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Keamanan
Data:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Akses
dari luar kampus berarti meningkatkan potensi risiko keamanan. Jaringan VPN
atau layanan cloud harus diimplementasikan dengan keamanan yang kuat untuk
melindungi data sensitif kampus dari akses yang tidak sah.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Kualitas
Koneksi Internet:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Ketergantungan
pada koneksi internet eksternal dapat menjadi masalah jika kualitas sinyal atau
kecepatan koneksi buruk. Dosen memerlukan akses yang andal dan stabil agar
dapat bekerja dengan efisien.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Kebutuhan
Konfigurasi Tambahan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Penting
untuk merencanakan dan menerapkan solusi ini dengan cermat untuk meminimalkan
risiko dan memastikan akses data real-time yang aman dan andal bagi dosen yang
menghadiri seminar di luar kampus. Penggunaan teknologi enkripsi, otentikasi
ganda, dan pengawasan akses secara ketat adalah beberapa langkah yang dapat
membantu meningkatkan keamanan dalam skenario ini.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>(4).</span></b><span
style='font-family:"Times New Roman",serif'> Untuk menyediakan akses internet
kepada tamu istimewa prodi dan mahasiswa prodi tanpa mengubah infrastruktur
fisik yang ada, berikut adalah solusi yang bisa diusulkan dengan
mempertimbangkan faktor keamanan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Solusi:
Penggunaan VLAN (Virtual Local Area Network)<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Arsitektur
Topologi:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>A.
Segmen &quot;TAMU&quot;:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Segmen
&quot;TAMU&quot; harus diisolasi sepenuhnya dari segmen lain dalam jaringan.
Penggunaan VLAN memungkinkan pembuatan segmen virtual ini tanpa perlu
menambahkan infrastruktur fisik baru.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Akses
internet diberikan melalui VLAN &quot;TAMU&quot; agar pengguna tamu dapat
terhubung ke internet secara terpisah dari jaringan internal prodi.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>B.
Segmen &quot;MAHASISWA PRODI&quot;:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Segmen
ini mencakup semua perangkat yang digunakan oleh mahasiswa di dalam program
studi tertentu. Perangkat dalam segmen ini dapat saling berkomunikasi, namun
tetap terisolasi dari segmen &quot;TAMU.&quot;<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>C.
Segmentasi Jaringan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>VLAN
untuk Segmen &quot;TAMU&quot;:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Pada
switch atau perangkat yang mengatur jaringan (misalnya router atau firewall), buat
VLAN khusus untuk tamu dengan jaringan IP yang terpisah dari segmen lain.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>VLAN
&quot;TAMU&quot; harus memiliki akses terbatas, hanya diizinkan untuk akses
internet dan dibatasi untuk tidak dapat mengakses jaringan internal lainnya.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>VLAN
untuk Segmen &quot;MAHASISWA PRODI&quot;:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Gunakan
VLAN terpisah untuk segmen &quot;MAHASISWA PRODI&quot; untuk memisahkan lalu
lintas dari segmen &quot;TAMU.&quot;<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Batasan
pada Segmen &quot;TAMU&quot;:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>1.
Pembatasan Akses:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Segmen
&quot;TAMU&quot; harus diberikan akses terbatas hanya untuk koneksi internet.
Tidak ada akses ke sumber daya jaringan internal prodi, termasuk server,
printer, atau perangkat lain yang ada di dalam jaringan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>2.
Pembatasan Waktu:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Akses
untuk segmen &quot;TAMU&quot; dapat diberlakukan dengan batas waktu tertentu.
Misalnya, setelah acara selesai atau sesuai dengan jadwal tamu istimewa, akses
ke segmen &quot;TAMU&quot; dapat dibatalkan atau dihentikan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>3.
Penggunaan Password:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Setiap
tamu harus diberikan akses menggunakan kata sandi (password) unik yang berlaku
untuk jangka waktu tertentu. Hal ini membantu dalam pelacakan dan pengawasan
akses oleh administrator jaringan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Dengan
mengimplementasikan solusi ini, perusahaan dapat menyediakan akses internet
yang aman dan terpisah bagi tamu istimewa prodi dan mahasiswa prodi tanpa
mengorbankan keamanan jaringan internal.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>(5).</span></b><span
style='font-family:"Times New Roman",serif'> Untuk menerapkan penggunaan mesin
absensi realtime terpusat dari server utama di gedung ketiga, berikut adalah
arsitektur solusi yang bisa diusulkan:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Server
Utama:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Di
gedung ketiga, didirikan server utama yang akan bertindak sebagai pusat
pengumpulan data dari semua mesin absensi di seluruh gedung kampus.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Server
ini bertanggung jawab untuk mengolah data absensi, menyimpan data dalam
database, dan menyediakan akses data realtime kepada pihak yang berwenang.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Mesin
Absensi di Setiap Gedung:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Setiap
gedung di kampus dilengkapi dengan mesin absensi yang terhubung ke jaringan
internal kampus.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Mesin-mesin
ini akan secara real-time mengirim data absensi ke server utama di gedung
ketiga.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Jaringan
Kampus:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Seluruh
gedung dalam kampus harus terhubung ke jaringan kampus yang terpercaya dan
aman.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Koneksi
antara mesin absensi dan server utama harus dilindungi dengan keamanan yang
kuat, seperti penggunaan VPN (Virtual Private Network) atau enkripsi untuk
melindungi data dalam perjalanan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Keamanan
dan Otorisasi:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Penggunaan
sistem otentikasi yang kuat diperlukan untuk memastikan hanya pihak yang
berwenang yang dapat mengakses data absensi.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Hak
akses harus diberikan secara tepat dan terbatas, berdasarkan peran dan tanggung
jawab masing-masing pengguna.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-family:"Times New Roman",serif'>Risiko
Keamanan yang Muncul:<o:p></o:p></span></b></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>A.
Potensi Titik Pintu Masuk Ancaman:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Setiap
zona, termasuk mesin absensi, dapat menjadi potensi titik pintu masuk bagi
ancaman keamanan. Penyusup dapat mencoba mengakses data absensi atau mengganggu
koneksi antara mesin dan server utama.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>B.
Pengiriman Data yang Tidak Aman:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Jika
data absensi dikirimkan melalui jaringan tanpa pengamanan yang memadai, dapat
terjadi potensi peretasan atau perangkap akses data (man-in-the-middle attack)
di perjalanan data.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><b><span style='font-size:12.0pt;
line-height:107%;font-family:"Times New Roman",serif'>Kesalahan Konfigurasi:<o:p></o:p></span></b></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Salah
konfigurasi pada mesin absensi atau server utama dapat menyebabkan kerentanan
keamanan yang tidak disengaja. Konfigurasi harus diperiksa dan dikelola secara
cermat.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>A.
Kehilangan Data:<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Potensi
kehilangan data karena kerusakan perangkat atau bencana alam harus dipertimbangkan,
dan solusi cadangan data harus diterapkan.<o:p></o:p></span></p>

<p class=MsoNormal style='text-align:justify'><span style='font-family:"Times New Roman",serif'>Untuk
mengatasi risiko ini, perlu dilakukan penerapan praktik keamanan yang ketat,
termasuk penggunaan firewall, VPN, enkripsi data, sistem otentikasi yang kuat,
pemantauan jaringan, dan tindakan pencegahan lainnya untuk melindungi data
absensi dan integritas sistem secara keseluruhan. Pembaruan dan patching sistem
secara berkala juga penting untuk mengurangi potensi kerentanan yang dapat
dieksploitasi oleh pihak yang tidak bertanggung jawab.<o:p></o:p></span></p>


</body>

</html>
